### ISSUE TITLE
just some education - c++ templates

### ISSUE THREAD

**Issue by mitchjs** [h2zero/esp-nimble-cpp#18]
@h2zero , you been busy.... i just pulled latest and my code compiles

trying to understand c++'s tempate

my code does: pCharacteristic->setValue(NVSReleaseFailCount); 

NVSReleaseFailCount is a uint32, so one doesnt need to do:  pCharacteristic->setValue<uint32_t>(NVSReleaseFailCount); 

do i have to do it on getValue? or will compiler know what type i need returned

**Comment by h2zero** [comment]
Hi @mitchjs setValue() doesn't need a type specified because the compiler knows the type you are passing as a parameter.

getValue() however does need the <type> specified as there is no parameter passed so it needs to be explicitly stated.

If you call getValue() without a <type> it will return a std::string. The template just converts the std::string to <type> for you.
